# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy WAR app to Azure Web App - WEBClientes-APP-Gilson

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9DA7F7F30C7D4BEC8A559BAAEDFBCE46 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_613B645CC24B43E480758C9A346021A4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D2311C6648D44232B19744A0A9FE4A1E }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'WEBClientes-APP-Gilson'
          slot-name: 'Production'
          package: './dist/CalculadoraIPWeb.war'

